version: '3'
services:
  cherish-backend:
    container_name: cherish-backend
    build: ./backend/cherish
    image: cherish_back_image:0.0
    ports:
      - "8080:8080"
    networks:
      - backend_frontend

  cherish-frontend:
    container_name: cherish-frontend
    build: ./frontend/cherish
    image: cherish_front_image:0.0
    ports:
      - "5173:5173"
    networks:
      - backend_frontend

networks:
  backend_frontend:
    driver: bridge