const instruction = "You will be provided with a conversation between a couple.\n"
+ "First, you must print `true` on the first line if the given context is worth saving, or `false` if it is not.\n"
+ "Then, followed by `:`, append the keyword of the context if it is worth saving, or an empty string if not.\n"
+ "The keyword must of course be a single word.\n"
+ "Thus, the first line must be either `true:keyword` or `false:`.\n\n"
+ "Next, on the second line, you must print `true` if the given context is something from which you can throw in an interesting topic, or `false` if not.\n"
+ "Similar to the first line, follow it with `:` and if there is an interesting topic to throw in, append that topic in one sentence; if not, append an empty string.\n"
+ "Therefore, the second line must also be strictly `true:one sentence` or `false:`.\n"
+ "Therefore, your answer must always be exactly 2 lines.\n\n"
+ "Below are some examples.\n\n"
+ "If I give you:\n"
+ "`A: Hi~\n"
+ "B: Hi~`\n"
+ "or\n"
+ "`A: Sleep well~\n"
+ "B: Yeah, you too, sleep well~`\n"
+ "This context is worth saving.\n"
+ "Because the beginning and end among a couple are precious.\n"
+ "However, it is not a context from which you can throw in an interesting topic.\n"
+ "Because greetings are a repetitive task done daily.\n"
+ "Therefore, for such a context, the output you should give is:\n"
+ "`true:Hi\n"
+ "false:`\n\n"
+ "Let me give you another example.\n"
+ "If I give you:\n"
+ "`A: What did you have for lunch today?\n"
+ "B: Just had ramen at home.`\n"
+ "This context is neither worth saving nor is it something from which you can throw in an interesting topic.\n"
+ "Because this context is not a moment signifying a beginning or an end like a greeting, and it's a very common topic that could be asked.\n"
+ "Therefore, for such a context, the output you should give is:\n"
+ "`false:\n"
+ "false:`\n\n"
+ "Let me give you another example.\n"
+ "If I give you:\n"
+ "`A: If we went on a space journey, which planet would you want to visit?\n"
+ "B: Mars might be somewhat livable, right?`\n"
+ "This context is not worth saving but is something from which you can throw in an interesting topic.\n"
+ "Because this context is not capturing a special emotion between a couple but it is not a very common topic and is something that can bring up an interesting topic.\n"
+ "Therefore, for such a context, you could give a somewhat funny and interesting output like:\n"
+ "`false:\n"
+ "true:How about investing in SpaceX stocks for Elon Musk?`\n\n"
+ "Let me give you another example.\n"
+ "If I give you:\n"
+ "`A: It's already been a year since we met.\n"
+ "B: Really, thank you for making good memories together until now.`\n"
+ "This context is worth saving but is not something from which you can throw in an interesting topic.\n"
+ "Because this context captures a special moment and emotion between a couple but is not a topic from which you can think of an interesting topic.\n"
+ "Therefore, for such a context, the output you should give is:\n"
+ "`true:anniversary\n"
+ "false:`\n\n"
+ "Lastly, i'll give you contexts in Korean and your answers, except for `true` and `false`, must always be in Korean.\n"
+ "And your Korean must always be polite and honorific."
;

export default instruction;
